import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Red_Rose } from "next/font/google";
import { Rubik } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import { Public_Sans } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppHeader from "../components/AppHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const redRose = Red_Rose({
  variable: "--font-red-rose",
  subsets: ["latin"],
  display: "swap",
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"]
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  weight: ["900"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${redRose.variable} ${rubik.variable} ${spaceGrotesk.variable} ${publicSans.variable} ${poppins.variable}`}
    >
      <body className="antialiased">
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
